<a href="https://colab.research.google.com/github/kaan9hesap/grafikTasarim/blob/main/numpy_2024_1947.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1) (10,15,30,45,60) değerlerine sahip numpy dizisi oluştur.

In [4]:
result=np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

# 2) 5-15 arasındaki sayılarla bir dizi oluştur.

In [5]:
result=np.arange(5,15)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 3) 50-100 arasında 5'er 5'er bir dizi oluştur.

In [6]:
result=np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

# 4) 10 elemanlı sıfırdan oluşan bir dizi oluşturunuz.

In [7]:
result=np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 5) 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

In [8]:
result=np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 6) 0-100 arasında eşit aralıklı 5 sayı üretin.



In [9]:
result=np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

# 7) 10-30 arasında rastgele 5 tamsayı üretin.

In [10]:
result=np.random.randint(10,30,5)
result

array([18, 28, 19, 25, 24])

# 8) -1 ile 1 arasında 10 adet sayı üretin.

In [11]:
result=np.random.randn(10)
result

array([-0.86170859, -0.66507991, -0.02277748,  0.36886881, -0.42646838,
       -1.71752861, -0.85835342,  0.75812104,  0.18606373, -0.9692679 ])

# 9) 3x5 boyutlarında 10-50 arasında rastgele bir matris oluşturunuz.

In [13]:
result=np.random.randint(10,50,15).reshape(3,5)
result

array([[36, 14, 22, 33, 40],
       [11, 47, 37, 41, 40],
       [48, 33, 12, 15, 28]])

# 10) Üretilen matrisin satır ve sütün sayıları toplamlarını hesaplayınız ?

In [14]:
matris=np.random.randint(10,50,15).reshape(3,5)
satir=matris.sum(axis=1)
sutun=matris.sum(axis=0)
print(satir)
print(sutun)

[176 143 162]
[ 72 119  64 108 118]


# 11) Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?



In [17]:
matris=np.random.randint(10,50,15).reshape(3,5)

result = matris.max()
print(result)

result = matris.min()
print(result)

result = matris.mean()
print(result)

47
12
34.666666666666664


# 12) Üretilen matrisin en büyük değerinin indexi kaçtır ?

In [18]:
matris=np.random.randint(10,50,15).reshape(3,5)

result = matris.argmax()
print(result)

result = matris.argmin()
print(result)

7
8


# 13) 10-20 arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

In [19]:
arr = np.arange(10,20)
print(arr)

result = arr[:3]
print(result)

result = arr[::-1]
print(result)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]


# 14) Üretilen dizinin elemanlarını tersten yazdırın.

In [20]:
result=arr[::-1]
result

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# 15) Üretilen matrisin ilk satırını seçiniz.

In [23]:
matris=np.random.randint(10,50,15).reshape(3,5)
result=matris[0]
result

array([39, 14, 11, 36, 47])

# 16) Üretilen matrisin 2. satır 3. sütundaki elemanı hangisidir ?

In [24]:
matris=np.random.randint(10,50,15).reshape(3,5)
result=matris[1,2]
result

47

# 17) Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

In [25]:
matris=np.random.randint(10,50,15).reshape(3,5)
result=matris[:, 0]
result

array([16, 31, 15])

# 18) Üretilen matrisin her bir elemanının karesini alınız.

In [26]:
matris=np.random.randint(10,50,15).reshape(3,5)
result=matris**2
result

array([[1369,  324,  400,  100,  676],
       [ 484,  961, 1444, 2025,  441],
       [2116,  400,  100,  225, 2304]])

# 19) Üretilen metris elemanlarının hangisi pozitif çift sayıdır?
# 19.1) Aralğı -50, +50 arasında yapınız.

In [27]:
matris=np.random.randint(10,50,15).reshape(3,5)
result = matris % 2 == 0
result

array([[ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True, False]])